INSERT INTO users (name, age) VALUES ("Anthony", 24);
INSERT INTO users (name, age) VALUES ("Bridget", 26);
INSERT INTO users (name, age) VALUES ("Peter", 20);
INSERT INTO users (name, age) VALUES ("Brian", 29);
INSERT INTO users (name, age) VALUES ("Tim", 29);
INSERT INTO users (name, age) VALUES ("Tom", 21);
INSERT INTO users (name, age) VALUES ("Ryan", 30);
INSERT INTO users (name, age) VALUES ("Lyon", 28);
INSERT INTO users (name, age) VALUES ("Susan", 35);
INSERT INTO users (name, age) VALUES ("Lisa", 23);
INSERT INTO users (name, age) VALUES ("Kate", 22);
INSERT INTO users (name, age) VALUES ("Allison", 30);
INSERT INTO users (name, age) VALUES ("Lydia", 22);
INSERT INTO users (name, age) VALUES ("Lacey", 26);
INSERT INTO users (name, age) VALUES ("Virginia", 25);
INSERT INTO users (name, age) VALUES ("Theresa", 27);
INSERT INTO users (name, age) VALUES ("Megan", 34);
INSERT INTO users (name, age) VALUES ("Emily", 38);
INSERT INTO users (name, age) VALUES ("Delia", 43);
INSERT INTO users (name, age) VALUES ("Ken", 32);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Capture Pocket", "technology", 1000000, "11/01/2019", "11/1/2020");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Magware", "food", 500000, "1/1/2019", "12/1/2019");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Electric Scooter", "technology", 1200000, "2/1/19", "3/1/2020");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Tempest", "weather", 400000, "3/1/19", 12/3/2019);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Up Close", "entertainment", 120000, "10/31/19", "11/30/2019");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Spirit Untamed", "calendar", 10000, "7/31/19", "8/30/19");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Taglioni Dance", "film", 200000, "5/3/19", "6/3/19");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Camp Bitter Lake", "story", 20000, "4/1/19", "5/1/19");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Barbarous 3", "comic", 30000, "3/31/19", "8/29/19");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Brady Tarot", "tarot", 23000, "3/20/19", "8/2/19");
INSERT INTO pledges (amount, user_id, project_id) VALUES (12000, 20, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 7, 2 );
INSERT INTO pledges (amount, user_id, project_id) VALUES (1300, 20, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (5000, 18, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1300, 4, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (23000, 9, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (13000, 14, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (230, 13, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1100, 19, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (4000, 10, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (3200, 18, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10000, 14, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20000, 19, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (7000, 10, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25000, 3, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (14324, 14, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (9234, 18, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (42389, 13, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (732, 10, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (4223, 4, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2342, 19, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (5323, 11, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (3424, 8, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (8362, 16, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (821, 15, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (5423, 18, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (423, 11, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (253, 14, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (8888, 8, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2352, 2, 8);
